### ISSUE TITLE
Avoid clip: true

### ISSUE THREAD

**Issue by kimmoal** [TestMyQt/material-outline#9]
Mention `clip: true` in delegates performance issue somewhere.

**Comment by kimmoal** [comment]
*Tino: I would add here that avoid using clip in the delegates. If clip is enabled, each delegate will be batched separately, i.e. there will be an OpenGL state change between each batch, which affects the rendering performance. By allowing the view (parent of the delegates) to do the clipping, there will be only one batch in the best case.*

**Comment by j4miol** [comment]
This is now mentioned in the material.
